name: Build and Deploy to K3s

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: temiayo/k3s-mission-control
  KUBECONFIG_PATH: /etc/rancher/k3s/k3s.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    needs: build
    runs-on:
      - self-hosted
      - linux
      - x64
      - k3s

    steps:
      - name: Sync EC2 runner with latest GitHub code
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0

      - name: Verify runner and cluster access
        run: |
          sudo kubectl --kubeconfig=${{ env.KUBECONFIG_PATH }} get nodes

      - name: Apply Kubernetes manifests
        run: |
          sudo kubectl --kubeconfig=${{ env.KUBECONFIG_PATH }} apply -f k8s/volume.yaml
          sudo kubectl --kubeconfig=${{ env.KUBECONFIG_PATH }} apply -f k8s/configmap.yml
          sudo kubectl --kubeconfig=${{ env.KUBECONFIG_PATH }} apply -f k8s/secret.yaml
          sudo kubectl --kubeconfig=${{ env.KUBECONFIG_PATH }} apply -f k8s/deployment.yaml
          sudo kubectl --kubeconfig=${{ env.KUBECONFIG_PATH }} apply -f k8s/service.yaml
          sudo kubectl --kubeconfig=${{ env.KUBECONFIG_PATH }} apply -f k8s/ingress.yaml

      - name: Update deployment image
        run: |
          sudo kubectl --kubeconfig=${{ env.KUBECONFIG_PATH }} set image deployment/mission-control mission-control=${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Wait for rollout
        run: |
          sudo kubectl --kubeconfig=${{ env.KUBECONFIG_PATH }} rollout status deployment/mission-control --timeout=180s

      - name: Show cluster status
        run: |
          sudo kubectl --kubeconfig=${{ env.KUBECONFIG_PATH }} get deployments
          sudo kubectl --kubeconfig=${{ env.KUBECONFIG_PATH }} get pods
          sudo kubectl --kubeconfig=${{ env.KUBECONFIG_PATH }} get svc